
name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    - run: npm ci
    - run: npm run build --if-present
    - run: npx mocha test/test.spec.js
    env:
      CI: true